language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  
env:
  #- DB=mysql
  - DB=mysqli

before_script:
  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS gameap_test;' -uroot; fi"
  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -uroot -h localhost gameap_test < tests/test.sql; fi"
  
script: tests/run_tests.sh

matrix:
  allow_failures:
    - php: 5.2
    - php: hhvm
    - php: 7
